import { z } from 'zod';
import type { AgentTool } from '../agent/types';
import { toolImages } from '../agent/types';
import {
  addAnnotation,
  describeAnnotation,
  getMapController,
  listAnnotations,
  listLayerInfos,
  removeAnnotation,
  type Geometry,
  type LayerInfo,
  type LayerStyle,
} from '../map/store';

/**
 * Map workspace tools (demo 10). This module only talks to the map through the controller registered by the map
 * pane (src/map/store.ts), so deck.gl / MapLibre stay in the lazily loaded map chunk. Outputs are compact: counts,
 * bbox, columns, legend; features never go into the model's context.
 */

const color = z.string().describe('Hex color like #e4572e (or a CSS color name)');
const styleSchema = z
  .object({
    color: color.optional().describe('Single fill color (points/polygons/cells) or line color'),
    color_by_column: z.string().optional().describe('Color features by this column (a numeric or categorical property)'),
    color_scheme: z.enum(['bins', 'categories', 'continuous']).optional().describe('bins (quantiles, default) | categories | continuous'),
    palette: z.string().optional().describe('CARTOColors palette name, e.g. PurpOr, Sunset, Teal, BluYl, Burg (sequential), Temps (diverging), Bold, Vivid, Safe (qualitative)'),
    domain: z.array(z.union([z.number(), z.string()])).optional().describe('bins: thresholds; categories: values; continuous: [min, max]. Default: computed from the data'),
    bins: z.number().int().min(2).max(7).optional().describe('Number of quantile classes for bins (default 5)'),
    radius: z.number().min(0.5).max(50).optional().describe('Point radius in pixels'),
    opacity: z.number().min(0).max(1).optional(),
    outline_color: color.optional(),
    outline_width: z.number().min(0).max(10).optional().describe('Outline width in pixels (line width for line layers)'),
    legend_title: z.string().max(80).optional().describe('Title shown in the legend'),
    visible: z.boolean().optional(),
  })
  .strict();

/** What the model sees about a layer. */
function compactLayer(l: LayerInfo) {
  return {
    id: l.id,
    name: l.name,
    kind: l.kind,
    status: l.status,
    ...(l.error && { error: l.error }),
    ...(l.warning && { warning: l.warning }),
    ...(l.featureCount !== undefined && { [l.kind === 'h3' ? 'source_rows' : 'features']: l.featureCount }),
    ...(l.bbox && { bbox: l.bbox }),
    ...(l.columns?.length && { columns: l.columns.slice(0, 30) }),
    ...(!l.visible && { visible: false }),
    legend: l.legend.items.length > 1 ? `${l.legend.title}: ${l.legend.items.map((i) => `${i.label} ${i.color}`).join(' | ')}` : l.legend.items[0]?.color,
  };
}

const geometrySchema = z
  .object({ type: z.enum(['Point', 'MultiPoint', 'LineString', 'MultiLineString', 'Polygon', 'MultiPolygon']), coordinates: z.array(z.any()) })
  .describe('GeoJSON geometry, [lon, lat] coordinates');

export function createMapTools(): AgentTool[] {
  const addCarto: AgentTool<any> = {
    name: 'map_add_carto_layer',
    description:
      'Add a tiled CARTO layer to the live map from a read-only BigQuery SELECT (or a table). No row limit: tiles are ' +
      'generated by CARTO. kind points|lines|polygons: the query must return a GEOGRAPHY column named geom (e.g. ' +
      'ST_GEOGPOINT(longitude, latitude) AS geom) plus any columns to style by. kind h3: return an H3 index column ' +
      'named h3 (e.g. `carto-un`.carto.H3_FROMGEOGPOINT(ST_GEOGPOINT(lon, lat), 7) AS h3) and give aggregation_exp ' +
      '(e.g. "COUNT(*) AS n" for raw rows, "SUM(n) AS n" for pre-aggregated cells); cells re-aggregate as you zoom. ' +
      'Returns id, feature/cell count, bbox, columns and legend. Re-using an id replaces that layer.',
    inputSchema: z
      .object({
        id: z.string().optional().describe('Layer id (default: derived from name)'),
        name: z.string().max(80).optional().describe('Human-readable layer name (legend)'),
        kind: z.enum(['points', 'lines', 'polygons', 'h3']),
        sql: z.string().optional().describe('A single read-only SELECT/WITH statement'),
        table: z.string().optional().describe('Fully qualified table project.dataset.table (instead of sql)'),
        geom_column: z.string().optional().describe('Geometry column (default geom)'),
        h3_column: z.string().optional().describe('H3 column (default h3)'),
        aggregation_exp: z.string().optional().describe('h3 only, required: e.g. "COUNT(*) AS n"'),
        aggregation_res_level: z.number().int().min(1).max(8).optional().describe('h3 only: cell detail per tile (default 4; higher = smaller cells)'),
        style: styleSchema.optional(),
      })
      .strict(),
    async execute(input) {
      const m = await getMapController();
      return compactLayer(await m.addCartoLayer(input));
    },
  };

  const addGeojson: AgentTool<any> = {
    name: 'map_add_geojson',
    description:
      'Add a small GeoJSON layer (≤ 20,000 features): either inline `geojson` (FeatureCollection, Feature, geometry) or ' +
      '`from_sql`, a read-only SELECT returning a geometry column named geom (GEOGRAPHY/GeoJSON/WKT) or longitude/latitude ' +
      'columns, plus properties. Use it for a few computed shapes or points (e.g. a buffer, the top-N locations).',
    inputSchema: z
      .object({
        id: z.string().optional(),
        name: z.string().max(80).optional(),
        geojson: z.any().optional(),
        from_sql: z.string().optional(),
        style: styleSchema.optional(),
      })
      .strict(),
    async execute(input, ctx) {
      const m = await getMapController();
      return compactLayer(await m.addGeojson(input, ctx.signal));
    },
  };

  const style: AgentTool<{ id: string } & LayerStyle> = {
    name: 'map_style_layer',
    description:
      'Change a layer\'s style: a single color, or color_by_column with color_scheme bins (quantiles) | categories | ' +
      'continuous and a CARTOColors palette; radius, opacity, outline, legend_title, visible. Only the given fields ' +
      'change. Returns the legend (class labels and colors).',
    inputSchema: styleSchema.extend({ id: z.string() }).strict() as any,
    async execute({ id, ...s }) {
      const m = await getMapController();
      return compactLayer(await m.styleLayer(id, s));
    },
  };

  const remove: AgentTool<{ id: string }> = {
    name: 'map_remove_layer',
    description: 'Remove a layer from the map.',
    inputSchema: z.object({ id: z.string() }),
    async execute({ id }) {
      const m = await getMapController();
      if (!m.removeLayer(id)) throw new Error(`No layer "${id}". Layers: ${listLayerInfos().map((l) => l.id).join(', ') || '(none)'}`);
      return { removed: id };
    },
  };

  const list: AgentTool<Record<string, never>> = {
    name: 'map_list_layers',
    description: 'List the map\'s layers (id, kind, status, feature counts, bbox, columns, legend) and the current view.',
    inputSchema: z.object({}),
    async execute() {
      const m = await getMapController();
      return { view: m.getView(), layers: listLayerInfos().map(compactLayer), annotations: listAnnotations().map((a) => a.id) };
    },
  };

  const setView: AgentTool<any> = {
    name: 'map_set_view',
    description: 'Move the map: center [lon, lat] + zoom (0–20), a bbox [west, south, east, north], or fit a layer / annotation.',
    inputSchema: z
      .object({
        center: z.array(z.number()).length(2).optional().describe('[lon, lat]'),
        zoom: z.number().min(0).max(20).optional(),
        bbox: z.array(z.number()).length(4).optional().describe('[west, south, east, north]'),
        fit_layer: z.string().optional(),
        fit_annotation: z.string().optional(),
      })
      .strict(),
    async execute(v) {
      const m = await getMapController();
      return await m.setView(v);
    },
  };

  const screenshot: AgentTool<Record<string, never>> = {
    name: 'map_screenshot',
    description:
      'Take a PNG screenshot of the map exactly as the user sees it (basemap, layers, annotations, legend), after tiles ' +
      'finish loading, and look at it. Use it to check your map and to describe spatial patterns you actually see.',
    inputSchema: z.object({}),
    async execute() {
      const m = await getMapController();
      const shot = await m.screenshot();
      const layers = listLayerInfos().filter((l) => l.visible).map((l) => l.id).join(', ') || 'none';
      const text = `Map screenshot ${shot.width}×${shot.height}px; center ${shot.view.center.join(', ')}, zoom ${shot.view.zoom}, ` +
        `bounds [${shot.view.bounds.join(', ')}]; visible layers: ${layers}; annotations: ${listAnnotations().map((a) => a.id).join(', ') || 'none'}.` +
        (shot.warning ? ` Warning: ${shot.warning}.` : '');
      return toolImages(text, [shot.image]);
    },
  };

  const getAnnotations: AgentTool<{ ids?: string[] }> = {
    name: 'get_annotations',
    description:
      'Get the annotations on the map: user-drawn (A1, A2…, with the user\'s note) and yours (M1…). Each has its geometry ' +
      'as compact GeoJSON ([lon, lat]) usable in BigQuery: ST_GEOGFROMGEOJSON(\'<geojson>\') with ST_INTERSECTS / ST_CONTAINS.',
    inputSchema: z.object({ ids: z.array(z.string()).optional().describe('Only these ids (default: all)') }),
    async execute({ ids }) {
      const want = ids?.map((i) => i.toUpperCase());
      const all = listAnnotations().filter((a) => !want || want.includes(a.id));
      return all.length ? all.map(describeAnnotation) : 'No annotations.';
    },
  };

  const annotate: AgentTool<{ point?: number[]; geometry?: Geometry; label?: string; remove_id?: string }> = {
    name: 'map_annotate',
    description:
      'Point something out to the user on the map: a labelled marker at `point` [lon, lat] or a labelled shape ' +
      '(`geometry`, GeoJSON). Gets an id M1, M2… Use remove_id to delete one of yours.',
    inputSchema: z
      .object({
        point: z.array(z.number()).length(2).optional().describe('[lon, lat]'),
        geometry: geometrySchema.optional(),
        label: z.string().max(80).optional().describe('Short label shown on the map (required unless remove_id)'),
        remove_id: z.string().optional(),
      })
      .strict(),
    async execute(input) {
      await getMapController();
      if (input.remove_id) {
        const id = input.remove_id.toUpperCase();
        if (!id.startsWith('M')) throw new Error('You can only remove your own annotations (M…)');
        removeAnnotation(id);
        return { removed: id };
      }
      const g: Geometry | undefined = input.geometry ?? (input.point ? { type: 'Point', coordinates: input.point } : undefined);
      if (!g) throw new Error('Pass point or geometry');
      if (!input.label) throw new Error('Pass a label');
      const a = addAnnotation(g, input.label, 'agent');
      return { id: a.id, label: a.note, type: g.type };
    },
  };

  return [addCarto, addGeojson, style, remove, list, setView, screenshot, getAnnotations, annotate];
}
